### ISSUE TITLE
class names are lost

### ISSUE THREAD

**Issue by Fil** [observablehq/notebook-runtime#115]
in http://visionscarto.net/observable-jekyll/explore/2018/05/24/breakout.html the template has
`<span id="highscore" class="classtest"></span>`

but the runtime _replaces_ `.classtest` by `.observablehq`

Expected behavior would be to add `.observablehq` (if that's feasible).

**Comment by jashkenas** [comment]
Good point, @Fil!

I've just released a **notebook-inspector** 1.1.1 that doesn't clobber existing classnames on the nodes that the inspector gets attached to.

Let me know if its still giving you any trouble.

https://github.com/observablehq/notebook-inspector/compare/v1.1.0...v1.1.1

**Comment by Fil** [comment]
Cool :) Tested it, but it doesn't look that the patch made it to
https://unpkg.com/@observablehq/notebook-runtime@1.1.2/dist/notebook-runtime.js?module
?

it still reads

if (!e) throw new Error("invalid node");this._node = e, e.className =
"observablehq";

and the github repo is not up-to-date either (still shows 1.1.0).

**Comment by mbostock** [comment]
Correct. The runtime is still running inspector 1.1.0.

**Comment by Fil** [comment]
got it! yes it works when I do
```
  import {Runtime} from "https://unpkg.com/@observablehq/notebook-runtime@1.1.1?module";
  import {Inspector} from "https://unpkg.com/@observablehq/notebook-inspector@1.1.1?module";
```

thanks!
